Add SSO and Authorization.
Rodmg/flugzeug pull request #19
Opened 2021-10-19 17:45 UTC by angelcaamal

Add SSO and Authorization.

2021-10-22 15:46 UTC, rodksquare commented on generators/app/templates/app/policies/Authentication.ts
> +import { NextFunction, Request, Response } from "express";
@angelcaamal There where important improvements done to this part, including adding custom permission support and a refactor, please check the **develop** branch of https://github.com/rodksquare/ks-cicd-minimal-backend-template/blob/develop/app/policies/Authorization.ts

2021-10-22 15:47 UTC, rodksquare requested changes
Please see the changes done on the **develop** branch of https://github.com/rodksquare/ks-cicd-minimal-backend-template and make sure to include them here

2021-10-22 17:01 UTC, angelcaamal commented on generators/app/templates/app/policies/Authentication.ts
> +import { NextFunction, Request, Response } from "express";
@rodksquare  Thanks, my mistake was taking master branch as example that does not have the latest changes. Working on it.

2021-10-28 17:37 UTC, rodksquare commented on generators/app/templates/package.json.template
> +    "passport": "^0.4.1",
passport and passport-google-oauth20 should go in dependencies, not dev

2021-11-02 15:38 UTC, rodksquare approved these changes

2021-11-02 15:38 UTC, rodksquare commented on generators/app/templates/package.json.template
> +    "passport": "^0.4.1",
Same for @the-ksquare-group/passport-microsoft

2021-11-02 15:57 UTC, merged